// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/acepanel/helper/internal/app"
	"github.com/acepanel/helper/internal/service"
	"github.com/acepanel/helper/internal/system"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

func initHelper() (*app.Helper, error) {
	executor := system.NewExecutor()
	detector := system.NewDetector(executor)
	firewall := system.NewFirewall(executor, detector)
	systemd := system.NewSystemd(executor)
	userManager := system.NewUserManager(executor)
	installer := service.NewInstaller(detector, executor, firewall, systemd, userManager)
	uninstaller := service.NewUninstaller(detector, executor, systemd)
	mounter := service.NewMounter(detector, executor)
	helper := app.NewHelper(installer, uninstaller, mounter)
	return helper, nil
}
